# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, ansiWlPprint, llvmGeneral, llvmGeneralPure }:

cabal.mkDerivation (self: {
  pname = "llvm-pp";
  version = "0.1.0.0";
  sha256 = "2d8506bf9bf895f3f378d3e35575e5c33b46654f9e7fd4ec25b52c9863a4df01"
  buildDepends = [ llvmGeneralPure ];
  meta = {
    homepage = "https://github.com/sdiehl/llvm-pp";
    description = "Pretty printer for LLVM IR";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
